// <auto-generated />
using System;
using DataLayer;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DataLayer.Migrations
{
    [DbContext(typeof(DBLibraryContext))]
    partial class DBLibraryContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("BusinessLayer.Continent", b =>
                {
                    b.Property<string>("ContinentCode")
                        .HasMaxLength(2)
                        .HasColumnType("char(2)")
                        .HasColumnName("continent_code")
                        .IsFixedLength();

                    b.Property<string>("ContinentName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("continent_name");

                    b.HasKey("ContinentCode")
                        .HasName("PRIMARY");

                    b.ToTable("continents", (string)null);
                });

            modelBuilder.Entity("BusinessLayer.Country", b =>
                {
                    b.Property<string>("CountryCode")
                        .HasMaxLength(2)
                        .HasColumnType("char(2)")
                        .HasColumnName("country_code")
                        .IsFixedLength();

                    b.Property<string>("ContinentCode")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("char(2)")
                        .HasColumnName("continent_code")
                        .IsFixedLength();

                    b.Property<string>("CountryName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("country_name");

                    b.HasKey("CountryCode")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "ContinentCode" }, "FK_CountriesContinents");

                    b.ToTable("countries", (string)null);
                });

            modelBuilder.Entity("BusinessLayer.Footballer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<int?>("Age")
                        .HasColumnType("int")
                        .HasColumnName("age");

                    b.Property<bool?>("Captain")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("captain");

                    b.Property<string>("CountryCode")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("char(30)")
                        .HasColumnName("country_code");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("first_name");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("last_name");

                    b.Property<decimal>("Price")
                        .HasPrecision(19)
                        .HasColumnType("decimal(19,2)")
                        .HasColumnName("price");

                    b.Property<decimal>("Salary")
                        .HasPrecision(19)
                        .HasColumnType("decimal(19,2)")
                        .HasColumnName("salary");

                    b.Property<int?>("ShirtNumber")
                        .HasColumnType("int")
                        .HasColumnName("shirt_number");

                    b.Property<int?>("TeamId")
                        .HasColumnType("int")
                        .HasColumnName("team_id");

                    b.Property<string>("TeamPosition")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("team_position");

                    b.Property<int?>("Trophies")
                        .HasColumnType("int")
                        .HasColumnName("trophies");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "CountryCode" }, "FK_FootballersCountries");

                    b.HasIndex(new[] { "TeamId" }, "FK_FootballersTeams");

                    b.ToTable("footballers", (string)null);
                });

            modelBuilder.Entity("BusinessLayer.Footballerstrophy", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<int?>("FootballerId")
                        .HasColumnType("int")
                        .HasColumnName("footballer_id");

                    b.Property<int?>("TrophyId")
                        .HasColumnType("int")
                        .HasColumnName("trophy_id");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "TrophyId" }, "FK_Employees");

                    b.HasIndex(new[] { "FootballerId" }, "FK_Programs");

                    b.ToTable("footballerstrophy", (string)null);
                });

            modelBuilder.Entity("BusinessLayer.Stadium", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<int?>("Capacity")
                        .HasColumnType("int")
                        .HasColumnName("capacity");

                    b.Property<string>("CountryCode")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("char(2)")
                        .HasColumnName("country_code")
                        .IsFixedLength();

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("name");

                    b.Property<string>("TownName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("town_name");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "CountryCode" }, "FK_StadiumCountries");

                    b.ToTable("stadium", (string)null);
                });

            modelBuilder.Entity("BusinessLayer.Team", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<string>("CoachName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("coach_name");

                    b.Property<string>("Colours")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("colours");

                    b.Property<string>("CountryCode")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("char(30)")
                        .HasColumnName("country_code");

                    b.Property<int?>("Founded")
                        .HasColumnType("int")
                        .HasColumnName("founded");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("name");

                    b.Property<string>("TeamStadium")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("team_stadium");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "CountryCode" }, "FK_TeamsCountries");

                    b.ToTable("teams", (string)null);
                });

            modelBuilder.Entity("BusinessLayer.Trophy", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<string>("ContinentCode")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("char(30)")
                        .HasColumnName("continent_code");

                    b.Property<string>("CountryCode")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("char(30)")
                        .HasColumnName("country_code");

                    b.Property<int?>("Footballers")
                        .HasColumnType("int")
                        .HasColumnName("footballers");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "ContinentCode" }, "FK_TrophiesContinents");

                    b.HasIndex(new[] { "CountryCode" }, "FK_TrophiesCountries");

                    b.ToTable("trophies", (string)null);
                });

            modelBuilder.Entity("BusinessLayer.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("longtext");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetime");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("longtext");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("longtext");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("longtext");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("ClaimType")
                        .HasColumnType("longtext");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("longtext");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("ClaimType")
                        .HasColumnType("longtext");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("longtext");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("longtext");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("RoleId")
                        .HasColumnType("varchar(255)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Name")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Value")
                        .HasColumnType("longtext");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("BusinessLayer.Country", b =>
                {
                    b.HasOne("BusinessLayer.Continent", "ContinentCodeNavigation")
                        .WithMany("Countries")
                        .HasForeignKey("ContinentCode")
                        .IsRequired()
                        .HasConstraintName("FK_CountriesContinents");

                    b.Navigation("ContinentCodeNavigation");
                });

            modelBuilder.Entity("BusinessLayer.Footballer", b =>
                {
                    b.HasOne("BusinessLayer.Country", "CountryCodeNavigation")
                        .WithMany("Footballers")
                        .HasForeignKey("CountryCode")
                        .IsRequired()
                        .HasConstraintName("FK_FootballersCountries");

                    b.HasOne("BusinessLayer.Team", "Team")
                        .WithMany("Footballers")
                        .HasForeignKey("TeamId")
                        .HasConstraintName("FK_FootballersTeams");

                    b.Navigation("CountryCodeNavigation");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("BusinessLayer.Footballerstrophy", b =>
                {
                    b.HasOne("BusinessLayer.Footballer", "Footballer")
                        .WithMany("Footballerstrophies")
                        .HasForeignKey("FootballerId")
                        .HasConstraintName("FK_Programs");

                    b.HasOne("BusinessLayer.Trophy", "Trophy")
                        .WithMany("Footballerstrophies")
                        .HasForeignKey("TrophyId")
                        .HasConstraintName("FK_Employees");

                    b.Navigation("Footballer");

                    b.Navigation("Trophy");
                });

            modelBuilder.Entity("BusinessLayer.Stadium", b =>
                {
                    b.HasOne("BusinessLayer.Country", "CountryCodeNavigation")
                        .WithMany("Stadium")
                        .HasForeignKey("CountryCode")
                        .IsRequired()
                        .HasConstraintName("FK_StadiumCountries");

                    b.Navigation("CountryCodeNavigation");
                });

            modelBuilder.Entity("BusinessLayer.Team", b =>
                {
                    b.HasOne("BusinessLayer.Country", "CountryCodeNavigation")
                        .WithMany("Teams")
                        .HasForeignKey("CountryCode")
                        .IsRequired()
                        .HasConstraintName("FK_TeamsCountries");

                    b.Navigation("CountryCodeNavigation");
                });

            modelBuilder.Entity("BusinessLayer.Trophy", b =>
                {
                    b.HasOne("BusinessLayer.Continent", "ContinentCodeNavigation")
                        .WithMany("Trophies")
                        .HasForeignKey("ContinentCode")
                        .IsRequired()
                        .HasConstraintName("FK_TrophiesContinents");

                    b.HasOne("BusinessLayer.Country", "CountryCodeNavigation")
                        .WithMany("Trophies")
                        .HasForeignKey("CountryCode")
                        .IsRequired()
                        .HasConstraintName("FK_TrophiesCountries");

                    b.Navigation("ContinentCodeNavigation");

                    b.Navigation("CountryCodeNavigation");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("BusinessLayer.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("BusinessLayer.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BusinessLayer.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("BusinessLayer.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BusinessLayer.Continent", b =>
                {
                    b.Navigation("Countries");

                    b.Navigation("Trophies");
                });

            modelBuilder.Entity("BusinessLayer.Country", b =>
                {
                    b.Navigation("Footballers");

                    b.Navigation("Stadium");

                    b.Navigation("Teams");

                    b.Navigation("Trophies");
                });

            modelBuilder.Entity("BusinessLayer.Footballer", b =>
                {
                    b.Navigation("Footballerstrophies");
                });

            modelBuilder.Entity("BusinessLayer.Team", b =>
                {
                    b.Navigation("Footballers");
                });

            modelBuilder.Entity("BusinessLayer.Trophy", b =>
                {
                    b.Navigation("Footballerstrophies");
                });
#pragma warning restore 612, 618
        }
    }
}
